apiVersion: v1
kind: Namespace
metadata:
  name: serverless-examples

apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: serverless-example-go
  namespace: serverless-examples
spec:
  template:
    spec:
      containers:
        - image: docker.io/kscout/go-serverless
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
path: /
